{
 "title": "Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) as \"NEW\\:\"\nFROM user\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
    },
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id) AS \"All Time\\:\"\nFROM user"
    }
   ]
  },
  {
   "title": "Delivered Version Notification",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  version_notification.created_at AS \"time\",\n  version.version as version,\n  COALESCE(COUNT(version_notification.chat_id), 0) as users\nFROM version_notification\ninner join version ON version.id = version_notification.version_id\ngroup by version.version\norder by version.version desc"
    }
   ]
  },
  {
   "title": "Last Active Users",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  user.updated_at AS \"time\",\n  user.username as UserName,\n  user.first_name as FirstName,\n  user.last_name as LastName,\n  user.id as \"user id\"\nFROM user\nWHERE\n  is_bot = 0 AND\n  $__timeFilter(updated_at)\norder by updated_at desc"
    }
   ]
  },
  { "title": "Bot stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sample_metrics_bot_worker[1m])",
     "legendFormat": "requests per minute"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sample_metrics_bot_usage[1m])",
     "legendFormat": "requests per minute"
    }
   ]
  },
  { "title": "Products/Carts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Products",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sample_metrics_bot_item{}" },
    { "expr": "sum(sample_metrics_bot_item{})", "legendFormat": "sum" }
   ]
  },
  {
   "title": "Carts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sample_metrics_bot_cart{}" }
   ]
  }
 ]
}